### ISSUE TITLE
App reverts to codepush version when new Binary is deployed

### ISSUE THREAD

**Issue by tavosansal** [Microsoft/cordova-plugin-code-push#219]
Hello,
I have the following scenario:
- App running version 1.3.7 
- We did a codepush for a small bugfix that we did not want to do a new review process for since we were making some changes anyways.
- It worked perfectly and bugfix was deployed successfully
- Created a new build (v1.4.0) and deployed it to Testflight for beta testing
- Installed the new version via Testflight
- App opens and immediately reverts to the old version of the app 

We can tell is the old version because the UI is totally different. If you completely delete version 1.3.7 and install app from Testflight then everything works as expected. Would appreciate some help on why this is happening and how we can fix it.
Thanks.

* cordova-plugin-code-push version: 1.9.2-beta
* Cordova version: Latest
* iOS/Android/Windows version: iOS
* Does this reproduce on a debug build or release build? Release
* Does this reproduce on a simulator, or only on a physical device? Physical

**Comment by tavosansal** [comment]
Was fixed by this: https://github.com/Microsoft/cordova-plugin-code-push/commit/fe418996fa4e1cdd10bf04aa2c47b1feb517bac0

There is no tag for this so you will have to do 
`cordova plugin add https://github.com/Microsoft/cordova-plugin-code-push`
to get those changes

**Comment by sergey-akhalkov** [comment]
Hello @tavosansal, we've recently released `cordova-plugin-code-push@1.9.3`, so the release also contains https://github.com/Microsoft/cordova-plugin-code-push/commit/fe418996fa4e1cdd10bf04aa2c47b1feb517bac0 commit fixing the issue.
Closing this for now, please feel free to reopen in case of any issues or questions.

**Comment by kinosang** [comment]
Still not work well with `cordova-plugin-code-push@1.9.3-beta` on iOS (didn't test on Android, so I don't know if the bug affects android)

**Comment by max-mironov** [comment]
Hello @kinosang - that looks strange.  
- What version of iOS you are running? 
- The issue is reproducing on real device only or also on simulator? 
- Do you have minimal reproduction steps so we can reproduce this issue also on our side (it would be great if you could also reproduce this on cordova code-push basic [sample app)](https://github.com/Microsoft/cordova-plugin-code-push/tree/master/samples/basic)?

**Comment by kinosang** [comment]
- I tested it on iOS 10.3 (Developer Beta).
- The issue reproduced on both real device and simulator.
- I'm trying to reproduce this on the sample now.

Here's what I did on my app:

1. I create a new release with `code-push release-cordova myApp-ios ios`.
1. Run the app on my device, it update automatically
1. Change some codes and use `cordova run ios` to deploy new binary to device
1. Run the app on device, it reverts to codepush version

**Comment by kinosang** [comment]
It works well now after a completely removing of my app from my device.

**Comment by max-mironov** [comment]
@kinosang. so is correct that after removing the app and reinstalling it again the issue has gone away?

**Comment by kinosang** [comment]
@max-mironov yes.

**Comment by max-mironov** [comment]
Ok @kinosang seems that somehow recent native changes of cordova-plugin-code-push were not correctly installed on device, I'm closing the issue for now, please reopen or create a new one in case you see any issues.
