### ISSUE TITLE
Partial Updates

### ISSUE THREAD

**Issue by zwacky** [Microsoft/cordova-plugin-code-push#44]
Is there a way to only release partial updates from the `www` folder?

e.g. there was only a small hotfix change in `app.routes.js`, i don't want to upload the whole `www` folder.

**Comment by lostintangent** [comment]
When you create a new release from the CLI, the CodePush service will actually generate a diff against the previous release so that users upgrading from it will only receive the delta. The service then stores the full release and the diff.

This currently only works when end-users are upgrading from the previous release, so if a user is running v1 and the latest CodePush release is v3, they will get the full www folder. But if they were running v2, they would just get the modified/new files. 

We plan to improve the diffing logic on the server to support partial updates that span multiple releases, but our current thinking is that the CLI would always expect you to upload the entire www folder and let the service create the diff.

Any feedback on this would be greatly appreciated!

**Comment by zwacky** [comment]
thank you for the explanation, @lostintangent.

maybe it would make sense to update the docs https://github.com/Microsoft/cordova-plugin-code-push#create-an-application-update-package to say the `www` folder is the only input.

**Comment by lostintangent** [comment]
That would definitely make sense! I actually thought those docs already stated that, but we obviously don't. Apologies for that :)

Ironically enough, I actually just updated the CLI docs to make this more clearly last night, but the Cordova SDK should clarify this as well: https://github.com/Microsoft/code-push/blob/master/cli/README.md

Thanks so much for pointing this out. I'll fix it later tonight.

**Comment by dlebu** [comment]
I added more details to the documentation. Thanks @zwacky for using CodePush and please keep the feedback coming.

**Comment by zwacky** [comment]
I'm getting this error. `Error: An error has occured while installing the package. Could not get the package start page`

when I upload the full `./platforms/android/assets/www` folder, the updates do work without problem *but* need to download the full folder *everytime*. no diffing of files.

then I remove everything but `src/app.js` with an extra console.log() line to see if it worked. afaik code push should be able to diff the differences. the code-push release finishes fast and the download inside the app runs fast as well (bc the update ain't 8mb anymore). but can't apply it because of above mentioned error message.

am I doing something wrong?

**Comment by lostintangent** [comment]
The server expects you to send the entire app with every release and it will handle creating the diff for you. When you upload just the app.js file, the server thinks you deleted every other file, including the index.html file, hence the error you're getting. If you simply release the entire www folder, everything will work and your users will get differential updates automatically.

I'll add more detail to the release command in the CLI to indicate this behavior.

**Comment by zwacky** [comment]
alright, I think I understand.

besides the try uploading only one file, I also uploaded the same folder twice with only an edit in `app.js`. the download seems to take a long time - as if I'm downloading the full www folder again without diffing.

**Comment by lostintangent** [comment]
Hmm ok interesting. We'll take a look at the diffing logic and see what might be going on here for you. If you just keep uploading the entire app and putting the extra perf hit, we'll report back later today with an update on diffs.

**Comment by zwacky** [comment]
thanks for looking into it @lostintangent, that diffing sounds like such a bomb

**Comment by dtivel** [comment]
I tested the server's diffing functionality in various scenarios (release, rollback, and promote).  In the scenario you describe (v1 -> v2), a v1 client received a diff update for the v2 release.  In the case of rollback (e.g.:  v1 -> v2 -> v3 -> v2), a v1 client received a diff update to the v2 release, while a v3 client received a full update back to the v2 release.

How long does your download take?

**Comment by zwacky** [comment]
i'm gonna test it today with the `size` property of the remotePackage, that should be working as stated in #51.

**Comment by epicfaace** [comment]
I'm still getting the error "Could not get the package start page." Using v1.10.10-beta on Android.

**Comment by epicfaace** [comment]
@max-mironov sure -- can you see my comment on #327 ?
